language: node_js

node_js:
    - stable

cache:
    directories:
        - node_modules

branches:
    only:
        - master
        - develop

install:
    - yarn global add codecov
    - yarn install

script:
    - yarn coverage

after_success:
    - yarn codecov
